### ISSUE TITLE
Hello I am having issue in Maya when browsing a photo 

### ISSUE THREAD

**Issue by hariskhan101** [Yuqian-He/3Dface-reconstruction-plugin#1]
I get the error 
"Error in Generate Mesh"
"File not Found"
 whenever I try to browse the image in maya.

What could be the issue regarding this problem? Please Assist me in this 
Thanks :)

**Comment by Yuqian-He** [comment]
Hi, sorry for the late reply. It seems like you installed it in the wrong path. 

Could you try sys.executable in your Maya Script Editor(Python), and print it out to check where is your Maya path?

**Comment by hariskhan101** [comment]
Yeah I've Checked it, it's in F:\Maya-2022\Maya2022\bin\maya.exe.

What did I installed in the wrong path, How can I solve this?

**Comment by Yuqian-He** [comment]
Try to install it in F:\Maya-2022\Maya2022\, and then check if it is possible to run.

**Comment by hariskhan101** [comment]
What should I install in F:\Maya-2022\Maya2022 ?

**Comment by hariskhan101** [comment]
I have added virtual environment and AI model in the root directory but
still having this error.
What could be the problem about the path issue?
Please assist me with this

**Comment by Yuqian-He** [comment]
Here is my path in root Maya:
Maya2022|--Alenv
                  |--released_v0.1

and in those two folders, mine is:
Alenv |--conda-meta
          |--DLLs
          |--include
......(and so on)

released_v0.1 |-- DFDN
                        |-- emotionNet
                        |-- faceRender
.....(and so on)

Check if your path is like this.

**Comment by hariskhan101** [comment]
Yeah my path is exactly the same as yours but still getting the error. Is
this somthing more that I should change

It is something to do with "facialDetail.py" file?

I think its unable to create .obj or .mtl file, due to which it can't
generate mesh

**Comment by hariskhan101** [comment]
# Traceback (most recent call last):
#   File "<maya console>", line 106, in generate_mesh
#   File "<maya console>", line 42, in showMesh
# RuntimeError: File not found.

This is the error

![Screenshot 2023-07-26 235532](https://github.com/Yuqian-He/3Dface-reconstruction-plugin/assets/111196879/e736792a-239e-4c8e-8044-9e00bc0e2de2)

**Comment by Yuqian-He** [comment]
Could you check if anything was generated in ”released_v0.1/results“？ If the AI module goes well, it will create a folder with your image name. Click it to check if the "result.obj" file is in that folder.

**Comment by Yuqian-He** [comment]
I did a lot of print in bridge.py, could you also check if there is anything printed out during the script running? It can help to check the path.

**Comment by hariskhan101** [comment]
Sorry to bother you again and again :(

Nope there is nothing with my image name in ”released_v0.1/results“. No
extra folder is created in that folder.

**Comment by Yuqian-He** [comment]
Okayy, that means the Ai model didn't run successfully. Could you describe it in more detail? After you run the Bridge.py in Maya script editor, did you see a window pop up? If you did, after you select the image, what information on the editor does it print out?

**Comment by hariskhan101** [comment]
[image: image.png]
I am getting just a name of image on editor

**Comment by hariskhan101** [comment]
[image: image.png]
After I click Generate then this error pops up.

**Comment by Yuqian-He** [comment]
Sorry, I cant see the image. Could you send it again?

**Comment by hariskhan101** [comment]
[image: image.png]

**Comment by hariskhan101** [comment]
[image: image.png]

**Comment by hariskhan101** [comment]
Now I am able to get the output of only those images whose output are
already created in ”released_v0.1/results“ (Like Manface, Womanface, nic01).

But,

I am getting that same error about Generate Mesh, Show Mesh and File Not
Found WHENEVER I select other images .

How can I use my images and release an output

I think AI model is not running successfully
:'(


[image: image.png]
[image: image.png]

**Comment by Yuqian-He** [comment]
Sorry, I still cant see the image. 

What if you try to put your image in "released_v0.1/samples" ? 

This code is a long time ago, and I use Windows. But now I changed my computer to MAC, so I cant test it until I get another Windows computer. Sorry for that. It may be the path is wrong. Sorry for that.

If you put your image in "released_v0.1/samples" and run successfully, I will check my code after I have a Windows computer. (This AI module can only run in Windows)

**Comment by hariskhan101** [comment]
Yeah let me check.

I am making some mistake in setting path or something.

I will show you the project_path and python_path.

I am so sorry for disturbing you again and again

**Comment by Yuqian-He** [comment]
No worries, cuz the code is just a course project, some functions may not be completed. And I just test it using my computer.   Let me know if it is a success after you put your image in "released_v0.1/samples" path.

**Comment by hariskhan101** [comment]
I tested it after putting image in "released_v0.1/samples" path but it
doesn't work

Please check this path, if this is correct or not. This code is of bridge.py

def run_ai(self):
        python_path=path+'\\AIenv\\python.exe'
        project_path=path+'\\released_v0.1\\facialDetails.py'

        inputImage_path = self.input_path
        print(inputImage_path)
        outputResult_path = os.path.abspath(path+'\\released_v0.1\\results')

**Comment by hariskhan101** [comment]
My sys.executable path is F:/maya-2022/maya2022/bin/maya.exe
As you said that your executable path is /maya-2022/maya2022/maya.exe

Does it make a difference? which is causing an error about not finding the
file.

Kindly have a look carefully at my path. I think there is a small mistake
in putting the appropriate path.

I have put in a lot of hardwork from the last couple of days, so kindly
help me out.
Thanking you in an anticipation :)

**Comment by Yuqian-He** [comment]
Hi, sorry for the late reply. I still cannot test it as I don't have a Windows computer.

The path should be alright. if you put all the stuff under F:/maya-2022/maya2022/. 

You can check my line 28 output, it will show the input image path, check the Maya script editor to see if the output is correct compared with your own input image path.

It seems AI module cant find the image. Sorry, I hardly cant see what exactly the problem is as I cant test it by myself.

**Comment by hariskhan101** [comment]
No worries, when I am running facialDetails.py file it gives an import
module error of torch/numpy and other packages Not Found. But they are
already installed.

Is nvidia graphic card necessary for running cuda?

**Comment by Yuqian-He** [comment]
Yes, an NVIDIA graphics card is necessary for running CUDA.

**Comment by hariskhan101** [comment]
Hello, Which version of torchvision and torchaudio should I install?
I am getting version error in both of these packages?

**Comment by Yuqian-He** [comment]
Hi, sorry I don't have the script and env for this project. You can download my virtual env as I mentioned in README. All the package versions should be there. Thanks!

**Comment by hariskhan101** [comment]
Sorry for disturbing you again.
I'm stuck in an issue
torch cuda is available ()>
False
Can you help me out in resolving this error??

**Comment by Yuqian-He** [comment]
Hi sorry for the delay.
This error means you dont have CUDA installed. First, check if CUDA is installed, which should be typically installed separately from PyTorch. After that, check if you installed NVIDIA correctly. Cuz, cuDNN is a GPU-accelerated library for deep neural networks. It is often required for running PyTorch with CUDA, but is a library when you install NVIDIA correctly.
